### ISSUE TITLE
Change title color from red to theme green

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/Blog#102]
Change the color of blogs title from red to green theme.
![image](https://user-images.githubusercontent.com/76901313/130751287-6ba42b04-7522-44c5-9204-6f6c7fa08235.png)

**Comment by vedant-jain03** [comment]
@nitin10s

**Comment by gouravmohanty7070** [comment]
Can I work on this issue?

**Comment by nitin10s** [comment]
Fixed in #103
