### ISSUE TITLE
Some part of Circuitverse Blog is not Responsive

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/Blog#104]
![bandicam 2021-09-02 16-16-28-010](https://user-images.githubusercontent.com/76901313/131830840-54ceb1b3-ddba-415b-82b1-ed24d70100c0.jpg)

- go to 'https://blog.circuitverse.org/posts/2021/i18n-final-report/'

**Comment by Aniket762** [comment]
I am interested! Can I work on this issue?

**Comment by vedant-jain03** [comment]
@Aniket762 actually I was about to start working in this issue after mentors allowed me to do.
You can try another one bro
But I am on it 
Hope you won't mind it

**Comment by Aniket762** [comment]
Okay @vedant-jain03 , best of luck!

**Comment by tachyons** [comment]
Can you check if the issue exists on upstream theme as well ?

**Comment by vedant-jain03** [comment]
> Can you check if the issue exists on upstream theme as well ?

You mean these : https://github.com/CircuitVerse/Blog/tree/master/themes

**Comment by tachyons** [comment]
Here https://github.com/gethugothemes/northendlab-light

**Comment by upsaurav12** [comment]
is this issue resolved already ??

**Comment by tanmoysrt** [comment]
> is this issue resolved already ??

The issue is part of the theme, so you need to do the changes in the theme, and then we can update that in this blog repo.
https://github.com/gethugothemes/northendlab-light
