### ISSUE TITLE
Misalignment in navbar in mobile view

### ISSUE THREAD

**Issue by vaibhavupreti** [CircuitVerse/Blog#158]
In mobile view at https://blog.circuitverse.org/ ... the nav items dropdown menu is misaligned at currently like this...
Current View-
![bg](https://user-images.githubusercontent.com/85568177/200595645-00b04522-5e29-4c53-bcc9-b57230586694.jpg)

Should be aligned right next to the circuitverse logo ... 

I am currently working on this issue.

**Comment by VaibhavUpreti** [comment]
@vedant-jain03 @nitin10s how does this look? wdyt?

**Comment by sambhavgupta0705** [comment]
Hey Can I work on this issue ?

**Comment by VaibhavUpreti** [comment]
Hey, This issue is yet to be approved by the maintainers. If approved, I have the commits stashed with me. You can browse the organisation for more issues :)

**Comment by tachyons** [comment]
You can fix it in the [upstream](https://github.com/gethugothemes/northendlab-light/tree/d3dbe87d2e7ca2234799bda9ff1dea913fe6ecca)
