### ISSUE TITLE
enhancment of footer of blog page

### ISSUE THREAD

**Issue by sambhavgupta0705** [CircuitVerse/Blog#160]
![Screenshot from 2022-11-25 01-04-33](https://user-images.githubusercontent.com/81870866/203803575-e2ca1ce0-bb6e-4155-9356-3dc660363f73.png)

In mobile view the footer of the blog page requires enhancement as it is very basic and gives a dull look

**Comment by sambhavgupta0705** [comment]
Hey @vedant-jain03 can you approve this issue?

**Comment by tachyons** [comment]
Footer pages serve the purpose well. `Dull` look is subjective. Could you please update the issue with what exactly is wrong with the footer? and what are you proposing instead?

**Comment by sambhavgupta0705** [comment]
The logo and Circuitverse name is not fully centrally aligned ,I thought of rectifying it.

**Comment by sambhavgupta0705** [comment]
Any updates @tachyons ?can I work on this issue?
