### ISSUE TITLE
contact us form taking empty fields

### ISSUE THREAD

**Issue by GarvitSinghal47** [CircuitVerse/Blog#163]
in the contact, us form of the blog any user is able to submit a completely blank form.

the demo video is attached.

I see this blog comes from Gethugothemes template, so want to know if changing in this repo after the fork will work or I need to create a pull request in the original repo as well.

if this issue need to be resolve in this repo plz assign it to me.

[Contact-Us.webm](https://user-images.githubusercontent.com/82756460/209767721-ed9e059b-15dd-4189-8a5c-eda081215702.webm)

**Comment by GarvitSinghal47** [comment]
@vedant-jain03 and @tachyons have a look at the issue , if needs to be resolved plz assign it to me.

**Comment by upsaurav12** [comment]
@tanmoysrt @Prerna-0202 this issue was opened previously so pls close this issue

**Comment by tachyons** [comment]
Fixed in https://github.com/CircuitVerse/Blog/pull/213
