### ISSUE TITLE
Bug:The Contact in the footer doesn't highlighted properly

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/Blog#182]
The Contact in the footer doesn't highlighted properly,it seems like normal text.So it should be either have color green like Circuitverse link or should be underlined
![Screenshot (272)](https://github.com/CircuitVerse/Blog/assets/138685168/2e0a5885-bfeb-459d-bffd-ca9c11a37e67)

**Comment by harshsharma-11** [comment]
@tachyons @vedant-jain03 @VaibhavUpreti please review the issue

**Comment by Sujal942** [comment]
please assign me this i want to merge my first pr.!!!

**Comment by tachyons** [comment]
This is part of the theme, you can suggest the change on the themes repo
