### ISSUE TITLE
bug:Search in the header should have boundaries

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/Blog#183]
:Search in the header should have boundaries because it doesn't seem that we are searching ,its look like we are editing the page.So for better experience it is recommended that input for serach has proper boundary area
![Screenshot (276)](https://github.com/CircuitVerse/Blog/assets/138685168/397674b0-da4f-4203-8b2a-59bb96e7cd54)

**Comment by harshsharma-11** [comment]
@tachyons @VaibhavUpreti @vedant-jain03 please check the issue

**Comment by tachyons** [comment]
This should be handled in the upstream project https://github.com/gethugothemes/northendlab-light-hugo
