### ISSUE TITLE
Alignment issues in the navbar of circuitverse Blog page

### ISSUE THREAD

**Issue by DhairyaMajmudar** [CircuitVerse/Blog#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the responsive view the the navbar is not showing the expected alignment .

### Steps To Reproduce

- Visit Blog Page of circuit verse website 
- Open the responsive view ( width < 400 )

### Expected Behavior

Logo and the hamburger menu must be aligned in a row instead of a column 

### Screenshots

![image](https://github.com/CircuitVerse/CircuitVerse/assets/124715224/7c5acb2a-6bb5-4527-af60-f806c26dd07b)

### Device Information [optional]

```markdown
- OS: Windows 11
- Browser: Firefox
- version:
```

### Are you working on this issue?

Yes

**Comment by DhairyaMajmudar** [comment]
@tanmoysrt Bhaiya pls. assign

**Comment by tanmoysrt** [comment]
> @tanmoysrt Bhaiya pls. assign

@DhairyaMajmudar, you have been assigned to the issue

**Comment by DhairyaMajmudar** [comment]
> > @tanmoysrt Bhaiya pls. assign
> 
> @DhairyaMajmudar, you have been assigned to the issue

Thank you Bhaiya 🙏

**Comment by tachyons** [comment]
https://github.com/gethugothemes/northendlab-light-hugo This should be handled on the upstream project
