### ISSUE TITLE
Changing old logos in the footer

### ISSUE THREAD

**Issue by DhairyaMajmudar** [CircuitVerse/Blog#186]
### Is your feature request related to a problem? Please describe

Changing the old logo of twitter ( bird ) to its new logo ( X ) in the footer section of the blog page 

### Describe the solution you'd like

I would like to solve this issue by replacing the old logo ( Bird ) with the new logo ( X ) of the twitter

### Additional context

**ScreenShot**
![image](https://github.com/CircuitVerse/CircuitVerse/assets/124715224/690200e2-66b9-4deb-a23d-affd39e72378)

### Are you working on this?

Yes

**Comment by DhairyaMajmudar** [comment]
@tanmoysrt Bhaiya pls. assign this issue to me

**Comment by tanmoysrt** [comment]
> @tanmoysrt Bhaiya pls. assign this issue to me

You have been assigned !

**Comment by DhairyaMajmudar** [comment]
> > @tanmoysrt Bhaiya pls. assign this issue to me
> 
> You have been assigned !

Thank you so much Bhaiya 😃

**Comment by tachyons** [comment]
You might want to address this on the upstream project https://github.com/gethugothemes/northendlab-light-hugo
