### ISSUE TITLE
reqeust for  changing of twitter logo to new one in Blog footer

### ISSUE THREAD

**Issue by YashGupt29** [CircuitVerse/Blog#193]
![Screenshot from 2023-10-15 10-58-03](https://github.com/CircuitVerse/Blog/assets/136692180/638de8c2-27e2-47af-8180-0c0bd5a64b64)
Description
update twitter logo to new one!

Are you working on this issue?
yes

**Comment by YashGupt29** [comment]
@tanmoysrt  can you please review this so that i can work on it

**Comment by YashGupt29** [comment]
@tanmoysrt  can you please review this so that i can work on it

**Comment by tachyons** [comment]
Duplicate of https://github.com/CircuitVerse/Blog/issues/186
