### ISSUE TITLE
Change secondary colour ( red -> darker shades of green/blue)

### ISSUE THREAD

**Issue by akshay1027** [CircuitVerse/Blog#58]
Changing headings colour( or secondary colour) from red to darker shades of green/blue would be good for UI.

**Comment by akshay1027** [comment]
let me know if this would be good for our community, I would like to work on this @sal2701 sir.

**Comment by sunnytyagi19** [comment]
does it still have issues? if yes then I would like to work on it.

**Comment by tachyons** [comment]
Thanks for the suggestion, We are using a theme and no plan to change it for now

**Comment by ShreyaPrasad1209** [comment]
@akshay1027 can you close this issue?

**Comment by akshay1027** [comment]
Sure, sorry!
