### ISSUE TITLE
Navbar Size

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/Blog#87]
* Problem Statement
The size of the navbar is too large. I will make it small and also add icons on menu bar links.

**Comment by vedant-jain03** [comment]
@ShreyaPrasad1209 What do you think mam, If is it a valid Issue?

**Comment by pavanjoshi914** [comment]
Navbar size looks appropriate to me. suitable with the theme as the same area is utilized for search also. still, you can present your work for an enhanced version of navbar and we can see what looks more appropriate.

**Comment by vedant-jain03** [comment]
Sure @pavanjoshi914 I will give you the sample screenshots within next 3 days and then you can compare which is looking more better.
Thankyou :)

**Comment by vedant-jain03** [comment]
![Screenshot (37)](https://user-images.githubusercontent.com/76901313/126265788-5cd476b9-7f6d-4b6d-ba70-22b9f4c13444.png)

@pavanjoshi914 What do you think of this enhancement?
I have changed the hover effect, width of logo and some small navbar bugs.

**Comment by pavanjoshi914** [comment]
> ![Screenshot (37)](https://user-images.githubusercontent.com/76901313/126265788-5cd476b9-7f6d-4b6d-ba70-22b9f4c13444.png)
> 
> @pavanjoshi914 What do you think of this enhancement?
> I have changed the hover effect, width of the logo, and some small navbar bugs.
> It is a hover effect on home link.!

LGTM!! lets wait for reply from @ShreyaPrasad1209

**Comment by vedant-jain03** [comment]
> > ![Screenshot (37)](https://user-images.githubusercontent.com/76901313/126265788-5cd476b9-7f6d-4b6d-ba70-22b9f4c13444.png)
> > @pavanjoshi914 What do you think of this enhancement?
> > I have changed the hover effect, width of the logo, and some small navbar bugs.
> > It is a hover effect on home link.!
> 
> LGTM!! lets wait for reply from @ShreyaPrasad1209

Sure

**Comment by ShreyaPrasad1209** [comment]
@vedant-jain03 we can change Home button from red to green to maintain consistency with the theme. Let's wait for @nitin10s's reply.

@nitin10s what do you think?

**Comment by vedant-jain03** [comment]
> @vedant-jain03 we can change Home button from red to green to maintain consistency with the theme. Let's wait for @nitin10s's reply.
> 
> @nitin10s what do you think?

Sure I will give green theme color in hover effect

**Comment by vedant-jain03** [comment]
@ShreyaPrasad1209 I have done with the edit you have told me to do. Should I raise PR

**Comment by nitin10s** [comment]
Hey Vedant, that's a nice observation, but why do you want to hide all the nav-links? The nav-links are shown so that the user can take a glance and understand what all we have to offer without clicking anywhere or anything

**Comment by vedant-jain03** [comment]
> Hey Vedant, that's a nice observation, but why do you want to hide all the nav-links? The nav-links are shown so that the user can take a glance and understand what all we have to offer without clicking anywhere or anything

Actually @nitin10s Their are only 2 navlinks (home and contact), I not hide them, just added hover effect in each as you can see home link with red background. 
In additional I have reduced the size of logo to 65%
and also fixes centralization of navbar.

**Comment by nitin10s** [comment]
What about the nav-links we currently have?

**Comment by vedant-jain03** [comment]
> What about the nav-links we currently have?

@nitin10s https://blog.circuitverse.org/ in this site I am not able to see nav-links more then home and contact with search and logo. Can you please tell me nitin , where I can see other navlinks?

**Comment by nitin10s** [comment]
oh my bad, I was referring to something else. Here what we could do, is completely remove the home button since clicking on the logo anyway directs home. Other than that, the logo fixes look good to me.

**Comment by nitin10s** [comment]
One more improvement we need is to change the red colour used to our characteristic green (if you could also fix that issue, in another PR)

**Comment by vedant-jain03** [comment]
> oh my bad, I was referring to something else. Here what we could do, is completely remove the home button since clicking on the logo anyway directs home. Other than that, the logo fixes look good to me.
> 
> Please go ahead and open PR for the same

Thanks for clearing the doubt nitin .
I will just remove the home button and make hover effects on contact only, and add green theme color to them.
give me thumbs up If I am right. I will just make change and raise PR then.

**Comment by vedant-jain03** [comment]
I have done changes in themes/northendlab-hugo , this is submodule. How can I push my code,? 
@pavanjoshi914 @ShreyaPrasad1209 @nitin10s
